// Backend will take less than - numbers, 7 means cost less than 7 million etc
export const menuItemLabelToCost = new Map<number, string>([
  [0, "No Filter"],
  [7, "< 7mil"],
  [10, "< 10mil"],
  [15, "<15mil"],
]);

export const menuItemLabelToNation = new Map<string, string>([
  ["AllNations", "No Filter"],
  ["AR", "Argentina"],
  ["AU", "Australia"],
  ["BE", "Belgium"],
  ["BR", "Brazil"],
  ["CM", "Cameroon"],
  ["CA", "Canada"],
  ["CR", "Costa Rica"],
  ["HR", "Croatia"],
  ["DK", "Denmark"],
  ["EC", "Ecuador"],
  ["GB", "England"],
  ["FR", "France"],
  ["DE", "Germany"],
  ["GH", "Ghana"],
  ["IR", "Iran"],
  ["JP", "Japan"],
  ["MX", "Mexico"],
  ["MA", "Morocco"],
  ["NL", "Netherlands"],
  ["PL", "Poland"],
  ["PT", "Portugal"],
  ["QA", "Qatar"],
  ["SA", "Saudi Arabia"],
  ["SN", "Senegal"],
  ["RS", "Serbia"],
  ["KR", "South Korea"],
  ["ES", "Spain"],
  ["CH", "Switzerland"],
  ["TN", "Tunisia"],
  ["US", "USA"],
  ["UY", "Uruguay"],
  ["GB", "Wales"],
]);
